This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./Master_Thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Master_Thesis.acn....done (10 entries accepted, 0 rejected).
Sorting entries....done (35 comparisons).
Generating output file Master_Thesis.acr....done (12 lines written, 0 warnings).
Output written in Master_Thesis.acr.
Transcript written in Master_Thesis.alg.
